### ISSUE TITLE
Windows binary?

### ISSUE THREAD

**Issue by elpatron68** [Junker/purple-xmpp-http-upload#10]
Is it possible to build a Windows binary of this plugin?

Regards,
Markus

**Comment by Junker** [comment]
sorry, i didn't check, have no Windows.

**Comment by drkui** [comment]
If the main author of this plugin can't port it to Windows, can someone with dev skills port this? It would be greatly appreciated for the majority of us Windows Pidgin users.

**Comment by EionRobb** [comment]
I've made a Windows build (PR with changes incoming)
[jabber_http_file_upload.zip](https://github.com/Junker/purple-xmpp-http-upload/files/2916726/jabber_http_file_upload.zip)

Also, I added the plugin to the list of third party plugins at
https://developer.pidgin.im/wiki/ThirdPartyPlugins#Miscellaneous
