### ISSUE TITLE
should I be able to drag and drop?

### ISSUE THREAD

**Issue by Carpintonto** [Junker/purple-xmpp-http-upload#13]
compiled and installed without errors, I have it enabled, but don't know how to use it!  

![Pidgin_XEP-0363](https://user-images.githubusercontent.com/3431272/62065087-16386d00-b1e3-11e9-9e21-49572aa2e244.png)

I tried dragging a file from gui file manager.

**Comment by Carpintonto** [comment]
running Pidgin 2.10.12 (libpurple 2.10.12) on Ubuntu 18.04.2 LTS with XFCE 4.12 (Xubuntu) using Thunar file manager

**Comment by Carpintonto** [comment]
just occurred:  also running OMEMO plugin - that just might be it.

**Comment by tbjorheim** [comment]
I tried this plugin today. I also use OMEMO. To upload a file, I open the conversation window for the user I like to send the file to, then click the "Conversation" menu, and then "More" and select "HTTP file upload". Seems to be working fine, at least for me. :)
