### ISSUE TITLE
Feature request: detect `lurch`, download and decrypt aesgcm:// media urls

### ISSUE THREAD

**Issue by petermolnar** [Junker/purple-xmpp-http-upload#22]
I'm using a combination of plugins with Pidgin to make it a more up to date client, including this plugin and [lurch](https://github.com/gkdr/lurch/) for OMEMO. 

In case OMEMO is enabled, the uploaded file itself should be encrypted as well. Is there a way to detect the existence of lurch and do the media encryption on upload?

(Note: I have modified this feature request after understanding that this module purely takes care of uploading, and has nothing to do with downloading.)

**Comment by petermolnar** [comment]
Correction: I'm starting to understand things better. This plugin should do the opposite: _encrypt_ the media, if lurch is present.

**Comment by Junker** [comment]
XEP-0363 doesn't have any specification for encryption.
If you mean (OMEMO Media sharing)[https://xmpp.org/extensions/inbox/omemo-media-sharing.html], this is not XEP, not approved yet.

For this purpose should use XEP-0448 (Encryption for stateless file sharing), in XEP-0448 specification they explain about encryption:
"Stateless file sharing (XEP-xxxx) describes a protocol that can be used to share files, previ-
ously uploaded using HTTP File Upload (XEP-0363), but lacks means of encrypting files. This
leaves files uploaded using HTTP File Upload (XEP-0363) without any standardized means of
encrypting them."
