### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by NuxRo** [Junker/purple-xmpp-http-upload#8]
Hi, it doesn't build on CentOS 7, see below:

purple-xmpp-http-upload]$ make
cc  -Wall -I. -g -pipe -fPIC -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libpurple   -I/usr/include/libxml2 -I./headers/jabber src/hfu_disco.c src/hfu_util.c src/jabber_http_file_upload.c -o jabber_http_file_upload.so -g -pipe -fPIC -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libpurple   -I/usr/include/libxml2 -I./headers/jabber -lgio-2.0 -lgobject-2.0 -lpurple -lglib-2.0    -lxml2 -lz -lm -ldl -L/usr/lib64/purple-2 -ldl -lm -ljabber -shared
/usr/bin/ld: cannot find -ljabber
collect2: error: ld returned 1 exit status
make: *** [jabber_http_file_upload.so] Error 1

**Comment by ekorneechev** [comment]
ping...
```
$ rpm -q libgio-devel glib2-devel libpurple-devel
libgio-devel-2.52.3-alt0.M80P.1
glib2-devel-2.52.3-alt0.M80P.1
libpurple-devel-2.10.12-alt2
$ make
cc  -Wall -I. -g -pipe -fPIC -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libpurple   -I/usr/include/libxml2 -I./headers/jabber src/hfu_disco.c src/hfu_util.c src/jabber_http_file_upload.c -o jabber_http_file_upload.so -g -pipe -fPIC -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libpurple   -I/usr/include/libxml2 -I./headers/jabber -lgio-2.0 -lgobject-2.0 -lpurple -lglib-2.0    -lxml2 -ldl -L/usr/lib64/purple-2 -ldl -lm -ljabber -shared
/usr/bin/ld: cannot find -ljabber

```

**Comment by Junker** [comment]
is it fedora?
For some reason on Fedora the lib is called libxmpp, not libjabber, so you have to replace -ljabber with -lxmpp.

**Comment by NuxRo** [comment]
Yep, that fixes it

**Comment by ekorneechev** [comment]
Thanks
PS AltLinux
