### ISSUE TITLE
Does not work over plain HTTP

### ISSUE THREAD

**Issue by ghost** [Junker/purple-xmpp-http-upload#9]
XEP-0363 Version 0.7.0 (2018-05-30) says: "The host MUST provide Transport Layer Security", but older versions don't. Some servers do not provide TLS. This plugin does not work on servers providing the HTTP upload service over plain HTTP.
I'd gladly contribute a solution but I'm stuck at radiocane/purple-xmpp-http-upload@9c8fcfecccfcc1eb8af576984aa5d00029b77851

**Comment by Junker** [comment]
Sorry, but i didn't plan to support plain HTTP protocol, because most of the servers support HTTPS.
But if you will provide full working patch(pull request), i will add it..
